version: "3"
services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - comsql:/var/lib/comsql
    ports:
      - '127.0.0.1:3306:3306'
volumes:
  comsql:
